# README

This site was generated by the [`infographiq`](https://github.com/marinebon/infographiq) package.

You can explore the various scenes with clickable silhouette images to reveal data driven status with plots.
